run:
  concurrency: 1
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-files: []

output:
  uniq-by-line: true
  print-linter-name: true

issues:
  exclude:
    - ".*getCssJsFiles` is unused"
    - "shadow: declaration of \"err\" shadows declaration at"

linters:
  disable-all: true
  enable:
    - bidichk
    - depguard
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - errname
    - bodyclose
    - contextcheck
    - containedctx
    - errchkjson
    - errorlint
    - forbidigo
    - goconst
    - makezero
    - whitespace
    - wrapcheck
    - zerologlint

linters-settings:
  govet:
    # Report about shadowed variables.
    # Default: false
    check-shadowing: true
    # Settings per analyzer.
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true
    # Disable all analyzers.
    # Default: false
    enable-all: true
  depguard:
    # Rules to apply.
    #
    # Variables:
    # - File Variables
    #   you can still use and exclamation mark ! in front of a variable to say not to use it.
    #   Example !$test will match any file that is not a go test file.
    #
    #   `$all` - matches all go files
    #   `$test` - matches all go test files
    #
    # - Package Variables
    #
    #  `$gostd` - matches all of go's standard library (Pulled from `GOROOT`)
    #
    # Default: Only allow $gostd in all files.
    rules:
      # Name of a rule.
      main:
        # List of file globs that will match this list of settings to compare against.
        # Default: $all
        files:
          - $all
        # List of allowed packages.
        allow:
          - $all
          - $gostd
          - github.com/caitunai/go-blueprint
          - github.com/rs/zerolog
          - github.com/spf13/viper
          - github.com/gin-gonic/gin
          - github.com/redis/go-redis
          - github.com/go-redis/cache
          - github.com/spf13/cobra
          - github.com/gin-contrib
          - github.com/golang-jwt/jwt
        # Packages that are not allowed where the value is a suggestion.
        deny:
          - pkg: "reflect"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package