run:
  concurrency: 1
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-files: []

output:
  uniq-by-line: true
  print-linter-name: true

issues:
  exclude:
    - ".*getCssJsFiles` is unused"

linters:
  disable-all: true
  enable:
    - bidichk
    - depguard
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - errname
    - bodyclose
    - contextcheck
    - containedctx
    - errchkjson
    - errorlint
    - forbidigo
    - goconst
    - makezero
    - whitespace
    - wrapcheck
    - zerologlint